# Generated by Django 4.0.4 on 2022-05-18 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_delete_comuna'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('codename', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BolFac',
            fields=[
                ('id_bol_fac', models.FloatField(primary_key=True, serialize=False)),
                ('precio', models.FloatField()),
            ],
            options={
                'db_table': 'bol_fac',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('patente', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_hora', models.FloatField()),
                ('id_producto', models.FloatField()),
                ('precio', models.FloatField()),
                ('cantidad', models.FloatField()),
            ],
            options={
                'db_table': 'detalle_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('action_flag', models.IntegerField()),
                ('change_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(blank=True, null=True)),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.FloatField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdPedido',
            fields=[
                ('id_orden', models.FloatField(primary_key=True, serialize=False)),
                ('fecha_orden', models.DateField()),
                ('precio', models.FloatField()),
                ('cantidad', models.FloatField()),
            ],
            options={
                'db_table': 'ord_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProdProv',
            fields=[
                ('id_producto', models.FloatField(primary_key=True, serialize=False)),
                ('fam_prod', models.CharField(max_length=20)),
                ('fec_venc', models.DateField()),
                ('precio', models.FloatField()),
                ('stock', models.FloatField()),
            ],
            options={
                'db_table': 'prod_prov',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProdServ',
            fields=[
                ('id_producto', models.FloatField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('precio_compra', models.FloatField()),
                ('precio_venta', models.FloatField()),
                ('stock', models.FloatField()),
                ('stock_critico', models.FloatField()),
                ('codificacion', models.FloatField()),
            ],
            options={
                'db_table': 'prod_serv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.FloatField(primary_key=True, serialize=False)),
                ('telefono', models.FloatField()),
                ('direccion', models.CharField(max_length=20)),
                ('rubro', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResHora',
            fields=[
                ('id_hora', models.FloatField(primary_key=True, serialize=False)),
                ('detalle', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'res_hora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.FloatField(primary_key=True, serialize=False)),
                ('tipo_servicio', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEmpleado',
            fields=[
                ('id_tipo_empleado', models.FloatField(primary_key=True, serialize=False)),
                ('tipo_empleado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tipo_empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProdProvProveedor',
            fields=[
                ('prod_prov_id_producto', models.OneToOneField(db_column='prod_prov_id_producto', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.prodprov')),
            ],
            options={
                'db_table': 'prod_prov_proveedor',
                'managed': False,
            },
        ),
    ]
